name = "ftnpay-worker"
main = "dist/index.js"      # 这里改成打包后文件的位置
compatibility_date = "2024-08-01"
type = "esm"

account_id = "cf3edee37551314c23bfb2bc2f2a7db5"
workers_dev = true

routes = [
   { pattern = "pay.ftnpay.com/*", zone_name = "ftnpay.com" }
]

kv_namespaces = [
  { binding = "ORDERS_KV", id = "a26264df40254bd8879786269fa1d6ec" }
]

[build]
command = "npm run build"
